// THIS FILE WAS GENERATED BY users_generator.py
#include "User1.h"
#include "info_data.h"

std::string User1::get() const {
    return getvalues(EType::EType1) + getvalues(EType::EType2) + getvalues(EType::EType3);
}
